### ISSUE TITLE
Roadmap?

### ISSUE THREAD

**Issue by kars0n777** [cherbie/soundcloud-tui#17]
I love the idea of the project, but what's the plan? As of right now it seems to be a test tui in rust. 

Let me know what's planned for the future of this project and I'll see what I can do.

**Comment by cherbie** [comment]
Hi @kars0n777, this is project I started to improve on my Rust knowledge. There are a variety of components that need to be developed. I am trying to apply TDD to my development process.

I am having issues currently with the UI layer (creating my own DOM like structure). I have reassessed my priorities and I'll likely just revisit that later.

Currently focused on audio processing. The soundcloud developers API make available a [HLS](https://developer.apple.com/streaming/) streaming service. I have learnt that this is something _spotify-tui_ didn't need to need to consider as they were able to make use of the underlying spotify _daemon_. So currently learning a bit about audio processing :)

Roadmap is constantly changing, however roughly:
1. audio processing
2. spotify user authentication flow (open browser & follow OAuth flow)
3. MVP UI system that can play a song via search

**Comment by kars0n777** [comment]
Thanks for letting me know, I love the idea of this program. I've used spotify-tui before and was always wondering if there was something similar for soundcloud. Also I use mpv as my main video player so the mpv ui sounds amazing. I don't know about sound processing or rust in general but I'll check in on this repo for if these problems are addressed. 

Jan 17, 2024, 5:08 AM by ***@***.***:

**Comment by cherbie** [comment]
So the sound processing has turned out to be quite tricky and I'm personally learning a LOT of new things (like HLS streaming). `spotify-tui` was able to make use of spotify's background daemon meaning the audio processing was handled outside the terminal application.

Hence they could focus on the UI layer and stay clear of actual music play complexities.

**Comment by genevera** [comment]
What about using `ffmpeg` or `gstreamer` libraries?

**Comment by cherbie** [comment]
Yeah that is definitely an option. I'm going to keep it as a last case scenario option for two reasons:

1. This is a project I am using to learn new things and streaming is quite interesting
2. There could be potentially a lot of overhead with `ffmpeg` having to fork a process, write to file and then probably read from file.

These are rough thoughts and I also haven't investigated `gstreamer`.

Initially though I don't mind trying to figure out how everything from Tiktok, to Youtube ... to SoundCloud itself works.
